### ISSUE TITLE
Memory leak in moira-filter service

### ISSUE THREAD

**Issue by JIexa24** [moira-alert/moira#560]
# BUG REPORT

## What version of Moira are you using (`[binary] --version`)?

<details><pre>

$ moira-filter --version
2.5.1.0

$ lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ uname -a
Linux moira 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

</pre></details>

## Configuration

<details>

`filter.yaml`

```yaml
# Use fields MasterName and SentinelAddrs to enable Redis Sentinel support,
# use Host and Port fields otherwise.
redis:
  # Sentinel cluster name
  master_name: ""
  # Sentinel address list, format: {host1_name:port};{ip:port}
  sentinel_addrs: ""
  # Node ip-address or host name
  host: "localhost"
  # Node port
  port: "6379"
  # Database id
  dbid: 0
  # Redis client connection pool size
  connection_limit: 512
graphite:
  # If true, graphite sender will be enabled.
  enabled: false 
  # If true, runtime stats will be captured and sent to graphite. Note: It takes to call stoptheworld() with configured "graphite.interval" to capture runtime stats (https://golang.org/src/runtime/mstats.go)
  runtime_stats: false
  # Graphite relay URI, format: ip:port
  uri: "graphite-relay:2003"
  # Moira metrics prefix. Use 'prefix: {hostname}' to use hostname autoresolver.
  prefix: DevOps.moira
  # Metrics sending interval
  interval: 60s
pprof:
  listen: ":8094"
filter:
  # Metrics listener uri
  listen: ":2003"
  # Retentions config file path. Simply use your original storage-schemas.conf or create new if you're using Moira without existing Graphite installation.
  retention_config: /etc/moira/storage-schemas.conf
  # Number of metrics to cache before checking them.
  # Note: As this value increases, Redis CPU usage decreases.
  # Normally, this value must be an order of magnitude less than graphite.prefix.filter.recevied.matching.count | nonNegativeDerivative() | scaleToSeconds(1)
  # For example: with 100 matching metrics, set cache_capacity to 10. With 1000 matching metrics, increase cache_capacity up to 100.
  cache_capacity: 10
  # Defines number of threads to match incoming graphite-metrics.
  # Equals to the number of processor cores found on Moira host by default or when variable is defined as 0.
  max_parallel_matches: 0
log:
  log_file: stdout
  log_level: warning

```

</details>

## What did you expect to see?
When a connection is accepted, handle-function does not create a thread waiting for a signal to terminate global processing of connections. Not seeing a major increase in memory usage.

## What did you see instead?
When moira-filter accepts a connection, a permanently blocked goroutine is created. As a consequence, their number grows, which leads to an increase in the used memory.
This calls the function:
https://github.com/moira-alert/moira/blob/e6d10e952af7328344a72262b23bca3c485e8dd0/filter/connection/handler.go#L39

I tried to comment this goroutine-call and recompile sources from github repo (tag: v2.5.1, go version: 1.13.1, service: filter). On the first application, this moment can be observed after 7/20 12:00, when the memory used graph is almost a horizontal line.

Screenshots of the problem:
![moiramemory](https://user-images.githubusercontent.com/17428720/88015652-eb5dcc00-cb4b-11ea-80a6-64101eaab6fe.png)

![Снимок экрана от 2020-07-20 15-44-27](https://user-images.githubusercontent.com/17428720/88015156-cc126f00-cb4a-11ea-8e4f-1a1923c1f0b2.png)
