### ISSUE TITLE
OpsGenie does not allow to change API endpoint used for notifications

### ISSUE THREAD

**Issue by damjanek** [moira-alert/moira#603]
# BUG REPORT

## What version of Moira are you using (`[binary] --version`)?

<details><pre>

$ api --version
/ # /usr/bin/api --version
Moira Api
Version: 2.5.0.0
Git Commit: 4c03982d9e87e38354a5b648971cda6f580811f3
Go Version: go1.11.5

$ notifier --version
/ # notifier --version
Moira Notifier
Version: MoiraVersion
Git Commit: git_Commit
Go Version: GoVersion

Notifier container is built from master.

</pre></details>

## Configuration

<details>

`notifier.yaml`

```yaml
redis:
  master_name: ""
  sentinel_addrs: ""
  host: "moira_redis"
  port: "6379"
  dbid: 0
  connection_limit: 512
graphite:
  enabled: true
  runtime_stats: false
  uri: "graphite.example.com:2003"
  prefix: moira
  interval: 60s
notifier:
  sender_timeout: 10s
  resending_timeout: "1:00"
  front_uri: "https://moira.example.com"
  timezone: Europe/Warsaw
  date_time_format: "15:04 02.01.2006"
  senders:
    -   api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
         type: opsgenie

  moira_selfstate:
    enabled: false
    remote_triggers_enabled: false
    redis_disconect_delay: 60s
    last_metric_received_delay: 120s
    last_check_delay: 120s
    last_remote_check_delay: 300s
    notice_interval: 300s
    contacts: []
remote:
  enabled: true
  url: "http://graphite.example.comi/render"
  user: user
  password: pass
  check_interval: 60s
  timeout: 300s
log:
  log_file: 'stdout'
  log_level: 'info'

```

</details>

## What did you expect to see?

OpsGenie sender should allow user to provide an API endpoint which is used for notifications.
This is essential, if you're running against EU OpsGenie endpoint (OpsGenie has two instances - EU and non-EU).

## What did you see instead?

https://github.com/moira-alert/moira/blob/master/senders/opsgenie/init.go#L39 - it should just include additional stanza when initializing the client with chosen api endpoint.
Also examples should mention ways to use different than default endpoint.
