### ISSUE TITLE
После обновления на 2.7.1 в вебе перестало отображаться последнее значение

### ISSUE THREAD

**Issue by proffust** [moira-alert/moira#743]
# BUG REPORT

## What version of Moira are you using (`[binary] --version`)?

<details><pre>

$ api --version
 docker exec -ti moira_api_1 api --version
2022/04/18 11:43:48 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
Moira Api
Version: 2.7.1.0
Git Commit: a52fbcd762e11fa48c4f63e465cca1840e929026
Go Version: go1.15.15

$ checker --version
docker exec -ti moira_checker_1 checker --version
2022/04/18 11:44:23 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
Moira Checker
Version: 2.7.1.0
Git Commit: a52fbcd762e11fa48c4f63e465cca1840e929026
Go Version: go1.15.15

$ filter --version
docker exec -ti moira_filter_1 filter --version
2022/04/18 11:45:43 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
Moira Filter
Version: 2.7.1.0
Git Commit: a52fbcd762e11fa48c4f63e465cca1840e929026
Go Version: go1.15.15

$ notifier --version
docker exec -ti moira_notifier_1 notifier --version
2022/04/18 11:46:00 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
Moira Notifier
Version: 2.7.1.0
Git Commit: a52fbcd762e11fa48c4f63e465cca1840e929026
Go Version: go1.15.15
</pre></details>
на всякий случай версии контейнеров
<details>
<pre>
CONTAINER ID   IMAGE                                     COMMAND                  CREATED       STATUS      PORTS                                       NAMES
9e8d40fc0bb1   nginx:alpine                              "/docker-entrypoint.…"   3 weeks ago   Up 6 days   0.0.0.0:80->80/tcp, :::80->80/tcp           moira_balancer_1
5a2674c5ccc2   moira/web2:2.5.1.0                        "/entrypoint.sh"         3 weeks ago   Up 6 days   80/tcp                                      moira_web_1
ee312bfd942a   harbor.sys.local/moira/notifier:2.7.1.0   "/usr/bin/notifier"      3 weeks ago   Up 6 days                                               moira_notifier_1
ed8ac53ba086   harbor.sys.local/moira/api:2.7.1.0        "/usr/bin/api"           3 weeks ago   Up 6 days   127.0.0.1:8081->8081/tcp                    moira_api_1
446ff34d935d   harbor.sys.local/moira/checker:2.7.1.0    "/usr/bin/checker"       3 weeks ago   Up 6 days                                               moira_checker_1
f092edd2fd67   harbor.sys.local/moira/filter:2.7.1.0     "/usr/bin/filter"        3 weeks ago   Up 6 days   0.0.0.0:2003->2003/tcp, :::2003->2003/tcp   moira_filter_1
9ad014a07274   harbor.sys.local/moira/filter:2.7.1.0     "/usr/bin/filter"        3 weeks ago   Up 6 days   0.0.0.0:2033->2003/tcp, :::2033->2003/tcp   moira_filter_4_1
942184b6bd8c   harbor.sys.local/moira/filter:2.7.1.0     "/usr/bin/filter"        3 weeks ago   Up 6 days   0.0.0.0:2013->2003/tcp, :::2013->2003/tcp   moira_filter_2_1
80c15e2005a7   harbor.sys.local/moira/filter:2.7.1.0     "/usr/bin/filter"        3 weeks ago   Up 6 days   0.0.0.0:2043->2003/tcp, :::2043->2003/tcp   moira_filter_5_1
9f89b1503ab0   harbor.sys.local/moira/filter:2.7.1.0     "/usr/bin/filter"        3 weeks ago   Up 6 days   0.0.0.0:2023->2003/tcp, :::2023->2003/tcp   moira_filter_3_1
8f1d6fef19ac   harbor.sys.local/moira/filter:2.7.1.0     "/usr/bin/filter"        3 weeks ago   Up 6 days   0.0.0.0:2053->2003/tcp, :::2053->2003/tcp   moira_filter_6_1
54788635455e   harbor.sys.local/library/redis:alpine     "docker-entrypoint.s…"   3 weeks ago   Up 6 days   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp   moira_redis_1
</pre>
</details>
и compose до кучи

<details>
<pre>
cat docker-compose.yml 
version: "3"

services:
  redis:
    image: harbor.sys.local/library/redis:alpine
    volumes:
      - /var/lib/docker/data/redis/:/data/
    restart: always
    ports:
      - "6379:6379"

  filter:
    image: harbor.sys.local/moira/filter:2.7.1.0
    hostname: filter_replica1
    ports:
      - "2003:2003"
    depends_on:
      - redis
    volumes:
      - ./moira-filter/:/etc/moira/
    links:
      - redis
    restart: always

  filter_2:
    image: harbor.sys.local/moira/filter:2.7.1.0
    hostname: filter_replica2
    ports:
      - "2013:2003"
    depends_on:
      - redis
    volumes:
      - ./moira-filter/:/etc/moira/
    links:
      - redis
    restart: always

  filter_3:
    image: harbor.sys.local/moira/filter:2.7.1.0
    hostname: filter_replica3
    ports:
      - "2023:2003"
    depends_on:
      - redis
    volumes:
      - ./moira-filter/:/etc/moira/
    links:
      - redis
    restart: always

  filter_4:
    image: harbor.sys.local/moira/filter:2.7.1.0
    hostname: filter_replica4
    ports:
      - "2033:2003"
    depends_on:
      - redis
    volumes:
      - ./moira-filter/:/etc/moira/
    links:
      - redis
    restart: always

  filter_5:
    image: harbor.sys.local/moira/filter:2.7.1.0
    hostname: filter_replica5
    ports:
      - "2043:2003"
    depends_on:
      - redis
    volumes:
      - ./moira-filter/:/etc/moira/
    links:
      - redis
    restart: always

  filter_6:
    image: harbor.sys.local/moira/filter:2.7.1.0
    hostname: filter_replica6
    ports:
      - "2053:2003"
    depends_on:
      - redis
    volumes:
      - ./moira-filter/:/etc/moira/
    links:
      - redis
    restart: always

  checker:
    image: harbor.sys.local/moira/checker:2.7.1.0
    hostname: checker_replica1
    depends_on:
      - redis
      - filter
      - filter_2
      - filter_3
    volumes:
      - ./moira-checker:/etc/moira/
    links:
      - redis
    restart: always

  notifier:
    #image: moira/notifier-unstable:2.5.1-feature-notifications-into-private-channels.2020-10-07.6b9a78d
    image: harbor.sys.local/moira/notifier:2.7.1.0
    hostname: notifier_replica1
    environment:
      HTTP_PROXY: http://
      HTTPS_PROXY: http://
    volumes:
      - ./moira-notifier/notifier.yml:/etc/moira/notifier.yml
#      - /etc/resolv.conf:/etc/resolv.conf
    depends_on:
      - redis
      - checker
    links:
      - redis
    restart: always

  api:
    image: harbor.sys.local/moira/api:2.7.1.0
    hostname: api_replica1
    depends_on:
      - redis
      - checker
    volumes:
      - ./moira-api:/etc/moira/
    links:
      - redis
    ports:
      - 127.0.0.1:8081:8081
    networks:
      - default
      - balancer
    restart: always

  web:
    image: moira/web2:2.5.1.0
    networks:
      - balancer
    restart: always

  balancer:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    networks:
      - balancer
    volumes:
      - ./moira-nginx/:/etc/nginx/conf.d/
    restart: always

networks:
  default: 
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/26
  balancer:
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.64/26
</pre>
</details>

## Configuration

<details>

`api.yaml`

```yaml
[root@p071i07app-moira01 moira-api]# cat api.yml 
redis:
  addrs: redis:6379
graphite:
  enabled: true
  runtime_stats: false
  uri: "192.168.226.166:2003"
  prefix: carbon.agents.moira.{hostname}
  interval: 10s
api:
  listen: ":8081"
  enable_cors: false
  web_config_path: "/etc/moira/web.json"
web:
  # Moira administrator email address
  supportEmail: "devops@example.com"
  # List of enabled contact types
  contacts:
    - type: mail
      label: E-mail
      validation: "^.+@.+\\..+$"
    - type: pushover
      label: Pushover
      placeholder: "Pushover user key"
    - type: slack
      label: Slack
      validation: "^[@#][a-zA-Z0-9-_]+"
      placeholder: "Slack #channel or @user"
    - type: telegram
      label: Telegram
      placeholder: "#channel, @username or group"
      help: "### To make things work you should:\n### In personal chat:\n - start conversation with bot [@zabbix_syslocal_bot](https://t.me/zabbix_syslocal_bot);\n - execute command `/start`;\n - type your login in above field as `@login`.\n\n### In group chat:\n - invite bot [@zabbix_syslocal_bot](https://t.me/zabbix_syslocal_bot) into chat;\n - execute command `/start@zabbix_syslocal_bot`;\n - bot will send you chat name, you should type it without extra characters in above field.\n\n### In channel:\n - add bot [@zabbix_syslocal_bot](https://t.me/zabbix_syslocal_bot) into channel;\n - promote bot as channel administrator;\n - type channel name in above field as `#channel`.\n"
    - type: twilio sms
      label: Twilio SMS
      validation: "^\\+79\\d{9}$"
      placeholder: "Phone number format +79*********"
    - type: twilio voice
      label: Twilio voice
      validation: "^\\+79\\d{9}$"
      placeholder: "Phone number format +79*********"
    - type: webhook
      label: My Webhook
      validation: "^(http|https):\\/\\/.*(example.com|example.org)(:[0-9]{2,5})?\\/"
      placeholder: "https://example.com/webhooks/moira"
      help: "### Domains whitelist:\n - example.com\n - example.org"
    - type: pagerduty
      label: PagerDuty
      placeholder: "Integration key"
    - type: opsgenie
      label: OpsGenie
      placeholder: "Responder Name or ID"
    - type: victorops
      label: VictorOps
      placeholder: "Routing key"
    - type: discord
      label: Discord
      placeholder: "Discord channel (eg: general-text) or user (eg: @user)"
remote:
  enabled: true
  url: "http://metrics.sys.local:8082/render"
  check_interval: 60s
  timeout: 60s
log:
  log_file: stdout
  log_level: info

```

`checker.yaml`

```yaml
redis:
  addrs: redis:6379
graphite:
  enabled: true
  runtime_stats: false
  uri: "192.168.226.166:2003"
  prefix: carbon.agents.moira.{hostname}
  interval: 10s
checker:
  nodata_check_interval: 60s
  check_interval: 30s
  metrics_ttl: 3h
  stop_checking_interval: 30s
remote:
  enabled: false
  url: "http://metrics.sys.local:8082/render"
  check_interval: 60s
  timeout: 60s
log:
  log_file: stdout
  log_level: info

```

`cli.yaml`

```yaml

```

`filter.yaml`

```yaml
redis:
  addrs: redis:6379
graphite:
  enabled: true
  runtime_stats: false
  uri: "192.168.226.166:2003"
  prefix: carbon.agents.moira.{hostname}
  interval: 10s
filter:
  listen: ":2003"
  retention_config: /etc/moira/storage-schemas.conf
  cache_capacity: 10
  max_parallel_matches: 0
log:
  log_file: stdout
  log_level: info
```

`notifier.yaml`

```yaml
redis:
  addrs: redis:6379
graphite:
  enabled: true
  runtime_stats: false
  uri: "192.168.226.166:2003"
  prefix: carbon.agents.moira.{hostname}
  interval: 10s
remote:
  enabled: false
  timeout: 60s
notifier:
  sender_timeout: 10s
  resending_timeout: "1:00"
  senders: 
    - type: mail
      mail_from: moira@sys.local
      smtp_host:XXXXXXXX
      smtp_port: 2561
      # Skip SMTP server certificate chain validation if false
      insecure_tls: true
      # Uses "mail_from" if empty
      #smtp_user: zabbix-rtk 
      #smtp_pass: XXXXXXXXXX
      # Email template file path (standard Go templates). By default use 'Fancy' template (see screenshot below). If empty, use build-in template with no markups and styles.
#      template_file: '/etc/moira/fancy-template.html'
    - type: telegram
      api_token: XXXXXXXXXXXXX
  moira_selfstate:
    enabled: true
    remote_triggers_enabled: false
    redis_disconect_delay: 60s
    last_metric_received_delay: 120s
    last_check_delay: 900s
    last_remote_check_delay: 900s
    notice_interval: 300s
    contacts:
      - type: mail
        value: denis.ustinov@rt.ru
  front_uri: http://moira.sys.local
  timezone: Europe/Moscow
  date_time_format: "15:04 02.01.2006"
log:
  log_file: stdout
  log_level: debug

```

</details>

## What did you expect to see?
последнее значение во фронте, при этом в запросе есть ответ(см скрин)
## What did you see instead?
![DeepinScreenshot_select-area_20220418155020](https://user-images.githubusercontent.com/33157540/163810885-4e4480bd-272d-469e-aaf2-69b88d41e1b4.png)
