### ISSUE TITLE
Can't send message WARNING

### ISSUE THREAD

**Issue by usbulat** [moira-alert/moira#81]
Hi

I'm trying to set up Moira.
Install it using released deb packages (from here https://github.com/moira-alert/moira/releases). Version 2.2.0-1

Trying to set notification, but no success.

notifier log shows:
WARNING	Can't send message after 41 try: Unknown contact type 'mail' [package of 1 notifications to user@domain.com]. Retry again after 1 min

--- notifier.yml
```
redis:
  host: localhost
  port: "6379"
  dbid: 0
graphite:
  enabled: true
  uri: "localhost:2003"
  prefix: DevOps.Moira
  interval: 60s
log:
  log_file: stdout
  log_level: debug
notifier:
  sender_timeout: 10s
  resending_timeout: "1:00"
  senders:
    - type: mail
      mail_from: moira
      smtp_host: smtp.gmail.com
      smtp_port: 465
      # Skip SMTP server certificate chain validation if false
      insecure_tls: true
      # Uses "mail_from" if empty
      smtp_user: user@domain.com
      smtp_pass: pass
      # Email template file path (standard Go templates), if empty use default template
      # template_file: ...
  moira_selfstate:
    enabled: true
    redis_disconect_delay: 60s
    last_metric_received_delay: 120s
    last_check_delay: 120s
    notice_interval: 300s
  front_uri: http://localhost
  timezone: Europe/Moscow
```

--- web.json
```
{
  "api_url": "/api",
  "contacts": [
    {"type": "mail", "validation": "^.+@.+\\..+$", "icon": "email"},
    {"type": "pushover", "validation": "", "img": "pushover.ico"},
    {"type": "slack", "validation": "^[@#].+$", "img": "slack.ico"},
    {"type": "telegram", "validation": "^@.+$", "img": "telegram.ico", "title": "@channel only", "help": "required to grant @KonturMoiraBot admin privileges"},
    {"type": "twilio sms", "img": "twilio_sms.ico"},
    {"type": "twilio voice", "img": "twilio_voice.ico"}
  ],
  "supportEmail": "user@domain.com"
}
```
