### ISSUE TITLE
checker memory leak

### ISSUE THREAD

**Issue by ihard** [moira-alert/moira#921]
# BUG REPORT

## What version of Moira are you using (`[binary] --version`)?

```
checker -version
2023/09/23 17:26:12 maxprocs: Leaving GOMAXPROCS=32: CPU quota undefined
Moira Checker
Version: 2.8.4
Git Commit: 2f5f4b314998a7f0a6d00b689ca9b8b251bfbb0f
```

## Configuration

<details>

`checker.yaml`

```yaml
---

redis:
  addrs: "10.10.88.101:6380,10.10.88.101:6381"
  dbid: 0
  connection_limit: 2048
  metrics_ttl: 6h
  dial_timeout: 1s
  read_timeout: 10s
  write_timeout: 10s
telemetry:
  listen: ":8092"
  pprof:
    enabled: true
  graphite:
    enabled: true
    runtime_stats: false
    uri: "127.0.0.1:2003"
    prefix: metric-server-1.moira.info
    interval: 60s
checker:
  nodata_check_interval: 120s
  check_interval: 60s
  lazy_triggers_check_interval: 10m
  stop_checking_interval: 180s
  max_parallel_checks: 16
  max_parallel_remote_checks: 0
remote:
  enabled: false
log:
  log_file: stdout
  log_level: info
```

pprof heap + goroutine
[pprof.zip](https://github.com/moira-alert/moira/files/12706697/pprof.zip)

Metric trigger queue
![2023-09-23_17-46-46](https://github.com/moira-alert/moira/assets/3078342/4755e3fb-0b58-4080-9d5e-cc6ad5a8483f)

Grafana Dashboard
![2023-09-23_18-14-54](https://github.com/moira-alert/moira/assets/3078342/109b5400-831d-4c7b-b34e-fefa3759e54f)
![2023-09-23_18-15-49](https://github.com/moira-alert/moira/assets/3078342/2e676546-b7fd-4a7e-97fc-7424479e30dd)
![2023-09-23_18-16-24](https://github.com/moira-alert/moira/assets/3078342/7d74da54-aae7-4dcf-a2e5-bbb1df9d9fd5)
![2023-09-23_18-17-14](https://github.com/moira-alert/moira/assets/3078342/ce9717a2-203e-4d3a-bdce-a023f536b61b)

</details>

## What did you expect to see?

no memory leak

## What did you see instead?

usage memory peak to 60GB and OOM
